name: GitHub Metrics

on:
  schedule:
    - cron: "0 8 * * *"  # обновляется каждый день в 8:00 UTC
  workflow_dispatch:

jobs:
  metrics-full:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.full.svg
          token: ${{ secrets.METRICS_TOKEN }}

          base: header, activity, community, repositories, metadata

          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_sections: most-used
          plugin_languages_limit: 8
          plugin_languages_indepth: yes

          plugin_repositories: yes

  metrics-languages:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8

  metrics-languages-indepth:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_indepth: yes
